management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxAttempts: 3
        waitDuration: 5s

  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitForPeriod: 1
        limitRefreshPeriod: 5s
        timeoutDuration: 1s

  CircuitBreaker:
    instances:
      inventoryCircuitBreaker:
        failureRateThreshold: 50   #If 50% of requests fail, then circuit breaker opens
        slidingWindowSize: 10  #Number of requests in a sliding window
        registerHealthIndicator: true  #Enables health indicator
        waitDurationInOpenState: 5s  #Duration of wait in open state
        permittedNumberOfCallsInHalfOpenState: 5  #Number of requests allowed in half-open state
        slidingWindowType: COUNT_BASED  #COUNT_BASED or TIME_BASED
        minimumNumberOfCalls: 5  #Minimum number of calls required before moving to half-open state
        automaticTransitionFromOpenToHalfOpenEnabled: true  #Enables automatic transition from open to half-open state